name: xflr5

services:
  xflr5:
    image: xflr5docker:latest
    build:
      dockerfile: Dockerfile
    group_add:
      - video
    devices:
      - /dev/dri:/dev/dri:rwm
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_DEBUG=verbose
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw